//FETCH PLAYER ACTION TYPE
export const FETCH_USERS_LIST = "FETCH_USERS_LIST";

//GET GENERAL ERRORS
export const GET_GENERAL_ERROR = "GET_GENERAL_ERROR";
//GET ERROR WHILE FETCHING USERLIST
export const FETCH_USER_LIST_ERROR = "FETCH_USER_LIST_ERROR";

//SELECT USERS TO PLAY
export const SELECT_USER = "SELECT_USER";
//REMOVE SELECTED USERS
export const REMOVE_USER = "REMOVE_USER";
